export const MATERIAL_CATEGORIES = [
  "Foundational",
  "Structural",
  "Interior Finishing",
  "Plumbing & Sanitary",
  "Exterior Finishing",
  "Electrical & Mechanical",
  "Consumables & Site",
  "Roofing",
  "Appliances",
  "General",
];

export const MATERIALS_LIST = [
  { name: "Cement (Type I)", category: "Foundational", unit: "bag (50kg)", typicalSupplier: "Local cement distributor" },
  { name: "Cement (Pozzolanic)", category: "Foundational", unit: "bag (50kg)", typicalSupplier: "Local cement distributor" },
  { name: "Sand (Fine)", category: "Foundational", unit: "m³", typicalSupplier: "Local quarry / sand supplier" },
  { name: "Sand (Coarse)", category: "Foundational", unit: "m³", typicalSupplier: "Local quarry / sand supplier" },
  { name: "Gravel / Crushed Stone", category: "Foundational", unit: "m³", typicalSupplier: "Local quarry / aggregate supplier" },
  { name: "Ready-Mix Concrete (C20/25)", category: "Foundational", unit: "m³", typicalSupplier: "Ready-mix plant" },
  { name: "Reinforcement Steel Bars (Y12)", category: "Foundational", unit: "tonne", typicalSupplier: "Steel yard / hardware" },
  { name: "Reinforcement Steel Bars (Y16)", category: "Foundational", unit: "tonne", typicalSupplier: "Steel yard / hardware" },
  { name: "Binding Wire", category: "Foundational", unit: "kg", typicalSupplier: "Hardware store" },
  { name: "Formwork Plywood (18mm)", category: "Foundational", unit: "sheet", typicalSupplier: "Timber/ply supplier" },
  { name: "Waterproofing Membrane (Bituminous)", category: "Foundational", unit: "roll", typicalSupplier: "Building materials store" },
  { name: "PVC Drainage Pipes (110mm)", category: "Foundational", unit: "length (3m)", typicalSupplier: "Plumbing supplier" },
  { name: "Concrete Blocks (Hollow 6\")", category: "Structural", unit: "piece", typicalSupplier: "Block factory / site-made" },
  { name: "Concrete Blocks (Solid 6\")", category: "Structural", unit: "piece", typicalSupplier: "Block factory" },
  { name: "Burnt Clay Bricks", category: "Structural", unit: "piece", typicalSupplier: "Brick kiln" },
  { name: "Stabilized Soil Blocks", category: "Structural", unit: "piece", typicalSupplier: "Local block maker" },
  { name: "Structural Timber (Hardwood 2x4\")", category: "Structural", unit: "length (3m)", typicalSupplier: "Timber market" },
  { name: "Structural Timber (Softwood 2x2\")", category: "Structural", unit: "length (3m)", typicalSupplier: "Timber market" },
  { name: "Steel I-Beam", category: "Structural", unit: "length", typicalSupplier: "Steel yard" },
  { name: "Roof Trusses (Prefabricated)", category: "Structural", unit: "set", typicalSupplier: "Roofing supplier" },
  { name: "Metal Roofing Sheets (Alu-Zinc)", category: "Structural", unit: "sheet", typicalSupplier: "Roofing supplier" },
  { name: "Roofing Tiles (Clay)", category: "Structural", unit: "piece", typicalSupplier: "Tile supplier" },
  { name: "Roofing Tiles (Concrete)", category: "Structural", unit: "piece", typicalSupplier: "Tile supplier" },
  { name: "Insulation (Fiberglass 50mm)", category: "Structural", unit: "roll", typicalSupplier: "HVAC supplier" },
  { name: "Insulation (Extruded Polystyrene)", category: "Structural", unit: "sheet", typicalSupplier: "Building materials store" },
  { name: "Drywall / Plasterboard (12.5mm)", category: "Structural", unit: "sheet", typicalSupplier: "Gypsum board supplier" },
  { name: "Gypsum Joint Compound", category: "Structural", unit: "bag", typicalSupplier: "Gypsum board supplier" },
  { name: "Structural Fasteners (Bolts & Nuts)", category: "Structural", unit: "kg", typicalSupplier: "Hardware store" },
  { name: "Ceramic Floor Tiles (600x600)", category: "Interior Finishing", unit: "m²", typicalSupplier: "Tile shop" },
  { name: "Porcelain Floor Tiles (600x600)", category: "Interior Finishing", unit: "m²", typicalSupplier: "Tile shop" },
  { name: "Vinyl Flooring (Roll)", category: "Interior Finishing", unit: "m²", typicalSupplier: "Flooring supplier" },
  { name: "Laminate Flooring (8mm)", category: "Interior Finishing", unit: "m²", typicalSupplier: "Flooring supplier" },
  { name: "Interior Paint (Emulsion)", category: "Interior Finishing", unit: "20L", typicalSupplier: "Paint dealer" },
  { name: "Primer/Undercoat", category: "Interior Finishing", unit: "20L", typicalSupplier: "Paint dealer" },
  { name: "Ceiling Boards (PVC)", category: "Interior Finishing", unit: "sheet", typicalSupplier: "Ceiling supplier" },
  { name: "Ceiling Boards (Gypsum)", category: "Interior Finishing", unit: "sheet", typicalSupplier: "Ceiling supplier" },
  { name: "Interior Doors (Flush)", category: "Interior Finishing", unit: "piece", typicalSupplier: "Joinery / door supplier" },
  { name: "Door Locks & Handles", category: "Interior Finishing", unit: "set", typicalSupplier: "Hardware store" },
  { name: "Skirting Boards (MDF)", category: "Interior Finishing", unit: "length (2.4m)", typicalSupplier: "Timber / decor supplier" },
  { name: "Aluminium Windows", category: "Interior Finishing", unit: "unit", typicalSupplier: "Aluminium fabricator" },
  { name: "UPVC Windows", category: "Interior Finishing", unit: "unit", typicalSupplier: "UPVC fabricator" },
  { name: "Glass (Tempered)", category: "Interior Finishing", unit: "m²", typicalSupplier: "Glass supplier" },
  { name: "Lighting Fixtures (LED)", category: "Interior Finishing", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "Switches & Sockets", category: "Interior Finishing", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "PPR Water Pipes (20mm)", category: "Plumbing & Sanitary", unit: "length (4m)", typicalSupplier: "Plumbing supplier" },
  { name: "PPR Water Pipes (32mm)", category: "Plumbing & Sanitary", unit: "length (4m)", typicalSupplier: "Plumbing supplier" },
  { name: "PVC Waste Pipes (110mm)", category: "Plumbing & Sanitary", unit: "length (3m)", typicalSupplier: "Plumbing supplier" },
  { name: "Water Storage Tank (1000L)", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Plumbing supplier" },
  { name: "Toilet (Close-Coupled)", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Sanitary ware dealer" },
  { name: "Wash Basin", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Sanitary ware dealer" },
  { name: "Kitchen Sink (Stainless)", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Sanitary ware dealer" },
  { name: "Mixer Tap / Faucet", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Sanitary ware dealer" },
  { name: "Water Heater (Instant 4.5kW)", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Electrical/Plumbing supplier" },
  { name: "Plumbing Fittings (Elbows/Tees/Unions)", category: "Plumbing & Sanitary", unit: "pack", typicalSupplier: "Plumbing supplier" },
  { name: "Exterior Paint (Weatherproof)", category: "Exterior Finishing", unit: "20L", typicalSupplier: "Paint dealer" },
  { name: "Fibre Cement Cladding Boards", category: "Exterior Finishing", unit: "sheet", typicalSupplier: "Cladding supplier" },
  { name: "Stone Veneer (Facing)", category: "Exterior Finishing", unit: "m²", typicalSupplier: "Stone supplier" },
  { name: "Gutters (Aluminium 125mm)", category: "Exterior Finishing", unit: "length (3m)", typicalSupplier: "Roofing supplier" },
  { name: "Downpipes (90mm)", category: "Exterior Finishing", unit: "length (3m)", typicalSupplier: "Roofing supplier" },
  { name: "Security Door (Steel)", category: "Exterior Finishing", unit: "unit", typicalSupplier: "Door supplier" },
  { name: "Fence Posts (Concrete)", category: "Exterior Finishing", unit: "piece", typicalSupplier: "Precast yard" },
  { name: "Chain Link / Wire Mesh", category: "Exterior Finishing", unit: "roll", typicalSupplier: "Hardware store" },
  { name: "Paving Stones (Interlocking)", category: "Exterior Finishing", unit: "m²", typicalSupplier: "Paver manufacturer" },
  { name: "CU Electrical Cable (2.5mm²)", category: "Electrical & Mechanical", unit: "roll (100m)", typicalSupplier: "Electrical supplier" },
  { name: "CU Electrical Cable (4mm²)", category: "Electrical & Mechanical", unit: "roll (100m)", typicalSupplier: "Electrical supplier" },
  { name: "MCB / Breakers", category: "Electrical & Mechanical", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "Distribution Board (12-Way)", category: "Electrical & Mechanical", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "Conduit Pipes (20mm)", category: "Electrical & Mechanical", unit: "length (3m)", typicalSupplier: "Electrical supplier" },
  { name: "Extract Fans", category: "Electrical & Mechanical", unit: "unit", typicalSupplier: "HVAC supplier" },
  { name: "AC Split Unit (1.5HP)", category: "Electrical & Mechanical", unit: "unit", typicalSupplier: "HVAC supplier" },
  { name: "Tile Adhesive", category: "Consumables & Site", unit: "bag (25kg)", typicalSupplier: "Tile shop" },
  { name: "Grout", category: "Consumables & Site", unit: "bag (20kg)", typicalSupplier: "Tile shop" },
  { name: "Silicone Sealant", category: "Consumables & Site", unit: "cartridge", typicalSupplier: "Hardware store" },
  { name: "Bitumen Sealant", category: "Consumables & Site", unit: "tin (4L)", typicalSupplier: "Hardware store" },
  { name: "Sandpaper (Assorted)", category: "Consumables & Site", unit: "pack", typicalSupplier: "Hardware store" },
  { name: "Nails & Screws (Assorted)", category: "Consumables & Site", unit: "kg", typicalSupplier: "Hardware store" },
  { name: "Protective Coatings (Anti-Rust)", category: "Consumables & Site", unit: "tin (4L)", typicalSupplier: "Hardware store" },
  { name: "Safety Helmets", category: "Consumables & Site", unit: "unit", typicalSupplier: "Safety supplier" },
  { name: "Safety Gloves", category: "Consumables & Site", unit: "pair", typicalSupplier: "Safety supplier" },
  { name: "Safety Boots", category: "Consumables & Site", unit: "pair", typicalSupplier: "Safety supplier" },
  { name: "Scaffolding (Rent per week)", category: "Consumables & Site", unit: "set/week", typicalSupplier: "Plant hire" },
];