export const MATERIAL_CATEGORIES = [
  "Foundations & Structural Work",
  "Structure & Framing", 
  "Roofing",
  "Masonry & Partitions",
  "Insulation & Waterproofing",
  "Joinery",
  "Electrical",
  "Plumbing & Sanitary",
  "Floor & Wall Coverings",
  "Hardware & Fasteners",
  "Exterior Materials & Roads & Utilities",
  "Miscellaneous Materials"
];

export const MATERIALS_LIST = [
  // Foundations & Structural Work
  { name: "Portland Cement", category: "Foundations & Structural Work", unit: "bag (50kg)", typicalSupplier: "Local cement distributor" },
  { name: "Pozzolanic Cement", category: "Foundations & Structural Work", unit: "bag (50kg)", typicalSupplier: "Local cement distributor" },
  { name: "Ready-mix Concrete (C20/25)", category: "Foundations & Structural Work", unit: "m³", typicalSupplier: "Ready-mix plant" },
  { name: "Ready-mix Concrete (C25/30)", category: "Foundations & Structural Work", unit: "m³", typicalSupplier: "Ready-mix plant" },
  { name: "Mortar mix", category: "Foundations & Structural Work", unit: "bag (25kg)", typicalSupplier: "Building materials store" },
  { name: "Sand (Fine)", category: "Foundations & Structural Work", unit: "m³", typicalSupplier: "Local quarry / sand supplier" },
  { name: "Sand (Medium)", category: "Foundations & Structural Work", unit: "m³", typicalSupplier: "Local quarry / sand supplier" },
  { name: "Sand (Coarse)", category: "Foundations & Structural Work", unit: "m³", typicalSupplier: "Local quarry / sand supplier" },
  { name: "Gravel (5/15)", category: "Foundations & Structural Work", unit: "m³", typicalSupplier: "Local quarry / aggregate supplier" },
  { name: "Gravel (15/25)", category: "Foundations & Structural Work", unit: "m³", typicalSupplier: "Local quarry / aggregate supplier" },
  { name: "Foundation stones", category: "Foundations & Structural Work", unit: "m³", typicalSupplier: "Stone supplier" },
  { name: "Concrete hollow blocks (8\")", category: "Foundations & Structural Work", unit: "piece", typicalSupplier: "Block factory" },
  { name: "Solid concrete blocks", category: "Foundations & Structural Work", unit: "piece", typicalSupplier: "Block factory" },
  { name: "Bond/chain blocks", category: "Foundations & Structural Work", unit: "piece", typicalSupplier: "Block factory" },
  { name: "Rebar Y8", category: "Foundations & Structural Work", unit: "tonne", typicalSupplier: "Steel yard" },
  { name: "Rebar Y10", category: "Foundations & Structural Work", unit: "tonne", typicalSupplier: "Steel yard" },
  { name: "Rebar Y12", category: "Foundations & Structural Work", unit: "tonne", typicalSupplier: "Steel yard" },
  { name: "Rebar Y20", category: "Foundations & Structural Work", unit: "tonne", typicalSupplier: "Steel yard" },
  { name: "Rebar Y28", category: "Foundations & Structural Work", unit: "tonne", typicalSupplier: "Steel yard" },
  { name: "Welded mesh", category: "Foundations & Structural Work", unit: "m²", typicalSupplier: "Steel yard" },
  { name: "Tie wire", category: "Foundations & Structural Work", unit: "kg", typicalSupplier: "Steel yard" },
  { name: "Formwork timber", category: "Foundations & Structural Work", unit: "m³", typicalSupplier: "Timber supplier" },
  { name: "Formwork plywood (18mm)", category: "Foundations & Structural Work", unit: "sheet", typicalSupplier: "Timber/ply supplier" },
  { name: "Form oil / release agent", category: "Foundations & Structural Work", unit: "L", typicalSupplier: "Building materials store" },
  { name: "Bituminous waterproofing membrane", category: "Foundations & Structural Work", unit: "roll", typicalSupplier: "Building materials store" },
  { name: "Geotextile", category: "Foundations & Structural Work", unit: "m²", typicalSupplier: "Building materials store" },
  { name: "Polyethylene film (under slab)", category: "Foundations & Structural Work", unit: "m²", typicalSupplier: "Building materials store" },
  { name: "Concrete admixtures (plasticizer/retarder)", category: "Foundations & Structural Work", unit: "L", typicalSupplier: "Building materials store" },
  { name: "Curing compound", category: "Foundations & Structural Work", unit: "L", typicalSupplier: "Building materials store" },
  { name: "Expansion joints (profiles)", category: "Foundations & Structural Work", unit: "m", typicalSupplier: "Building materials store" },
  { name: "Rebar spacers/chairs", category: "Foundations & Structural Work", unit: "piece", typicalSupplier: "Steel yard" },
  { name: "Precast lintels", category: "Foundations & Structural Work", unit: "piece", typicalSupplier: "Precast yard" },
  { name: "Precast concrete columns", category: "Foundations & Structural Work", unit: "piece", typicalSupplier: "Precast yard" },
  { name: "Prefabricated grade beams", category: "Foundations & Structural Work", unit: "piece", typicalSupplier: "Precast yard" },

  // Structure & Framing
  { name: "Joists / Beams (timber)", category: "Structure & Framing", unit: "m³", typicalSupplier: "Timber supplier" },
  { name: "Chevrons / Battens (timber)", category: "Structure & Framing", unit: "m³", typicalSupplier: "Timber supplier" },
  { name: "Glulam beam", category: "Structure & Framing", unit: "m³", typicalSupplier: "Timber supplier" },
  { name: "LVL (laminated veneer lumber)", category: "Structure & Framing", unit: "m³", typicalSupplier: "Timber supplier" },
  { name: "OSB board", category: "Structure & Framing", unit: "sheet", typicalSupplier: "Timber supplier" },
  { name: "Skirting Boards (MDF)", category: "Structure & Framing", unit: "m", typicalSupplier: "Timber supplier" },
  { name: "Plywood structural (18mm)", category: "Structure & Framing", unit: "sheet", typicalSupplier: "Timber supplier" },
  { name: "Steel beam IPN/HEA/HEB", category: "Structure & Framing", unit: "tonne", typicalSupplier: "Steel yard" },
  { name: "Angle / flat steel", category: "Structure & Framing", unit: "tonne", typicalSupplier: "Steel yard" },
  { name: "Joint hangers / brackets", category: "Structure & Framing", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Perforated connector plates", category: "Structure & Framing", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Chemical anchors", category: "Structure & Framing", unit: "cartridge", typicalSupplier: "Hardware store" },
  { name: "Prop (adjustable)", category: "Structure & Framing", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Strapping / bracing tape", category: "Structure & Framing", unit: "m", typicalSupplier: "Hardware store" },
  { name: "Sill / top plates", category: "Structure & Framing", unit: "m", typicalSupplier: "Timber supplier" },
  { name: "Ridge beam / purlins", category: "Structure & Framing", unit: "m", typicalSupplier: "Timber supplier" },
  { name: "Wood preservative", category: "Structure & Framing", unit: "L", typicalSupplier: "Hardware store" },
  { name: "Anti-rust primer (steel)", category: "Structure & Framing", unit: "L", typicalSupplier: "Hardware store" },

  // Roofing
  { name: "Clay roof tiles", category: "Roofing", unit: "m²", typicalSupplier: "Tile supplier" },
  { name: "Concrete roof tiles", category: "Roofing", unit: "m²", typicalSupplier: "Tile supplier" },
  { name: "Corrugated sheets", category: "Roofing", unit: "m²", typicalSupplier: "Roofing supplier" },
  { name: "Metal roofing (trapezoidal / IBR / acier)", category: "Roofing", unit: "m²", typicalSupplier: "Roofing supplier" },
  { name: "Bitumen shingles", category: "Roofing", unit: "m²", typicalSupplier: "Roofing supplier" },
  { name: "Under-roof membrane / breather", category: "Roofing", unit: "m²", typicalSupplier: "Roofing supplier" },
  { name: "Battens", category: "Roofing", unit: "m", typicalSupplier: "Timber supplier" },
  { name: "Counter-battens", category: "Roofing", unit: "m", typicalSupplier: "Timber supplier" },
  { name: "Ridge / verge / valley accessories", category: "Roofing", unit: "m", typicalSupplier: "Roofing supplier" },
  { name: "PVC gutters", category: "Roofing", unit: "m", typicalSupplier: "Roofing supplier" },
  { name: "Zinc/tile gutters", category: "Roofing", unit: "m", typicalSupplier: "Roofing supplier" },
  { name: "Downpipes", category: "Roofing", unit: "m", typicalSupplier: "Roofing supplier" },
  { name: "Leaf guards / outlets", category: "Roofing", unit: "piece", typicalSupplier: "Roofing supplier" },
  { name: "Roof window / skylight", category: "Roofing", unit: "piece", typicalSupplier: "Roofing supplier" },
  { name: "EPDM/PVC roofing membrane", category: "Roofing", unit: "m²", typicalSupplier: "Roofing supplier" },
  { name: "Roofing mastics / adhesives", category: "Roofing", unit: "L", typicalSupplier: "Roofing supplier" },
  { name: "Roof ventilation accessories", category: "Roofing", unit: "piece", typicalSupplier: "Roofing supplier" },

  // Masonry & Partitions
  { name: "Clay bricks", category: "Masonry & Partitions", unit: "piece", typicalSupplier: "Brick kiln" },
  { name: "Concrete hollow blocks (8\")", category: "Masonry & Partitions", unit: "piece", typicalSupplier: "Block factory" },
  { name: "Concrete solid blocks", category: "Masonry & Partitions", unit: "piece", typicalSupplier: "Block factory" },
  { name: "Autoclaved aerated concrete blocks", category: "Masonry & Partitions", unit: "piece", typicalSupplier: "Block factory" },
  { name: "Plasterboard (12.5mm standard)", category: "Masonry & Partitions", unit: "sheet", typicalSupplier: "Gypsum board supplier" },
  { name: "Plasterboard (moisture resistant)", category: "Masonry & Partitions", unit: "sheet", typicalSupplier: "Gypsum board supplier" },
  { name: "Plasterboard (fire-rated)", category: "Masonry & Partitions", unit: "sheet", typicalSupplier: "Gypsum board supplier" },
  { name: "Metal studs & tracks", category: "Masonry & Partitions", unit: "m", typicalSupplier: "Hardware store" },
  { name: "Joint tape & joint compound", category: "Masonry & Partitions", unit: "roll", typicalSupplier: "Gypsum board supplier" },
  { name: "Gypsum/lime/cement renders", category: "Masonry & Partitions", unit: "bag", typicalSupplier: "Building materials store" },
  { name: "The adhesive (mortar)", category: "Masonry & Partitions", unit: "bag", typicalSupplier: "Building materials store" },
  { name: "Corner beads / edge profiles", category: "Masonry & Partitions", unit: "m", typicalSupplier: "Hardware store" },
  { name: "Precast lintels", category: "Masonry & Partitions", unit: "piece", typicalSupplier: "Precast yard" },
  { name: "PU foam (gap filler)", category: "Masonry & Partitions", unit: "cartridge", typicalSupplier: "Hardware store" },
  { name: "Expansion joints (partition)", category: "Masonry & Partitions", unit: "m", typicalSupplier: "Hardware store" },
  { name: "Adhesives for boards", category: "Masonry & Partitions", unit: "L", typicalSupplier: "Hardware store" },
  { name: "Spacers / tile spacers", category: "Masonry & Partitions", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Lime mortar", category: "Masonry & Partitions", unit: "bag", typicalSupplier: "Building materials store" },

  // Insulation & Waterproofing
  { name: "Glass wool (rolls/panels)", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "HVAC supplier" },
  { name: "Rock wool (panels)", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "HVAC supplier" },
  { name: "Cellulose insulation", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "HVAC supplier" },
  { name: "EPS (expanded polystyrene)", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "Building materials store" },
  { name: "XPS (extruded polystyrene)", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "Building materials store" },
  { name: "PIR/PUR boards", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "Building materials store" },
  { name: "Cork boards", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "Building materials store" },
  { name: "Wood fiber boards", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "Building materials store" },
  { name: "Vapour barrier membrane", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "Building materials store" },
  { name: "Vapour control layer (VCL)", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "Building materials store" },
  { name: "Stickiness tapes/adhesives", category: "Insulation & Waterproofing", unit: "roll", typicalSupplier: "Building materials store" },
  { name: "PU/Silicone sealant", category: "Insulation & Waterproofing", unit: "cartridge", typicalSupplier: "Hardware store" },
  { name: "Expanding foam", category: "Insulation & Waterproofing", unit: "cartridge", typicalSupplier: "Hardware store" },
  { name: "Waterproof render/slurry", category: "Insulation & Waterproofing", unit: "bag", typicalSupplier: "Building materials store" },
  { name: "Bitumen torch-on membrane", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "Building materials store" },
  { name: "EPDM membrane", category: "Insulation & Waterproofing", unit: "m²", typicalSupplier: "Building materials store" },
  { name: "Damp-proof course (DPC)", category: "Insulation & Waterproofing", unit: "m", typicalSupplier: "Building materials store" },
  { name: "Resilient acoustic strip", category: "Insulation & Waterproofing", unit: "m", typicalSupplier: "Building materials store" },

  // Joinery
  { name: "Interior doors (pre-hung)", category: "Joinery", unit: "piece", typicalSupplier: "Joinery / door supplier" },
  { name: "Exterior door", category: "Joinery", unit: "piece", typicalSupplier: "Joinery / door supplier" },
  { name: "UPVC Windows", category: "Joinery", unit: "unit", typicalSupplier: "UPVC fabricator" },
  { name: "PVC window", category: "Joinery", unit: "unit", typicalSupplier: "UPVC fabricator" },
  { name: "Glass (Tempered)", category: "Joinery", unit: "m²", typicalSupplier: "Glass supplier" },
  { name: "Aluminium window", category: "Joinery", unit: "unit", typicalSupplier: "Aluminium fabricator" },
  { name: "Wooden window", category: "Joinery", unit: "unit", typicalSupplier: "Joinery supplier" },
  { name: "Sliding patio door", category: "Joinery", unit: "unit", typicalSupplier: "Joinery / door supplier" },
  { name: "Roller shutters", category: "Joinery", unit: "unit", typicalSupplier: "Shutter supplier" },
  { name: "Insect screens", category: "Joinery", unit: "m²", typicalSupplier: "Screen supplier" },
  { name: "Frames / casings", category: "Joinery", unit: "m", typicalSupplier: "Joinery supplier" },
  { name: "Sills / thresholds", category: "Joinery", unit: "m", typicalSupplier: "Joinery supplier" },
  { name: "Locks & cylinders", category: "Joinery", unit: "set", typicalSupplier: "Hardware store" },
  { name: "Handles & roses", category: "Joinery", unit: "set", typicalSupplier: "Hardware store" },
  { name: "Hinges / butt hinges", category: "Joinery", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Perimeter seals / weatherstrips", category: "Joinery", unit: "m", typicalSupplier: "Hardware store" },
  { name: "Closer/arm / hardware kits", category: "Joinery", unit: "set", typicalSupplier: "Hardware store" },
  { name: "Security grilles", category: "Joinery", unit: "m²", typicalSupplier: "Security supplier" },

  // Electrical
  { name: "Cable (1.5mm² lighting)", category: "Electrical", unit: "roll (100m)", typicalSupplier: "Electrical supplier" },
  { name: "Cable (2.5mm² switched)", category: "Electrical", unit: "roll (100m)", typicalSupplier: "Electrical supplier" },
  { name: "Cable (4mm² power)", category: "Electrical", unit: "roll (100m)", typicalSupplier: "Electrical supplier" },
  { name: "Flexible conduit (ICTA)", category: "Electrical", unit: "m", typicalSupplier: "Electrical supplier" },
  { name: "Rigid conduit / trunking", category: "Electrical", unit: "m", typicalSupplier: "Electrical supplier" },
  { name: "Conduit Pipes (20mm)", category: "Electrical", unit: "length (3m)", typicalSupplier: "Electrical supplier" },
  { name: "Extract fans", category: "Electrical", unit: "unit", typicalSupplier: "HVAC supplier" },
  { name: "Fluorescent tubes", category: "Electrical", unit: "piece", typicalSupplier: "Electrical supplier" },
  { name: "Junction boxes", category: "Electrical", unit: "piece", typicalSupplier: "Electrical supplier" },
  { name: "Switches", category: "Electrical", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "AC Split Unit (1.5HP)", category: "Electrical", unit: "unit", typicalSupplier: "HVAC supplier" },
  { name: "Wall sockets", category: "Electrical", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "RJ45 / TV outlets", category: "Electrical", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "Distribution board (12-Way) / enclosure", category: "Electrical", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "MCBs / RCDs", category: "Electrical", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "Surge protectors / contactors", category: "Electrical", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "DIN rail accessories", category: "Electrical", unit: "piece", typicalSupplier: "Electrical supplier" },
  { name: "LED luminaires / spots", category: "Electrical", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "LED panels / ceiling lights", category: "Electrical", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "Cable trays / clips", category: "Electrical", unit: "m", typicalSupplier: "Electrical supplier" },
  { name: "Electrical tape / heat-shrink", category: "Electrical", unit: "roll", typicalSupplier: "Electrical supplier" },

  // Plumbing & Sanitary
  { name: "PPR pipes (water)", category: "Plumbing & Sanitary", unit: "length (4m)", typicalSupplier: "Plumbing supplier" },
  { name: "PEX / Multilayer pipes", category: "Plumbing & Sanitary", unit: "length (4m)", typicalSupplier: "Plumbing supplier" },
  { name: "Copper pipes", category: "Plumbing & Sanitary", unit: "length (4m)", typicalSupplier: "Plumbing supplier" },
  { name: "PPR Water Pipes (20mm)", category: "Plumbing & Sanitary", unit: "length (4m)", typicalSupplier: "Plumbing supplier" },
  { name: "PPR Water Pipes (32mm)", category: "Plumbing & Sanitary", unit: "length (4m)", typicalSupplier: "Plumbing supplier" },
  { name: "PVC Waste Pipes (110mm)", category: "Plumbing & Sanitary", unit: "length (3m)", typicalSupplier: "Plumbing supplier" },
  { name: "Fittings (elbows/tees/couplers)", category: "Plumbing & Sanitary", unit: "piece", typicalSupplier: "Plumbing supplier" },
  { name: "Pipe clamps / supports", category: "Plumbing & Sanitary", unit: "piece", typicalSupplier: "Plumbing supplier" },
  { name: "Shut-off valves / check valves", category: "Plumbing & Sanitary", unit: "piece", typicalSupplier: "Plumbing supplier" },
  { name: "Basin/Sink mixer taps", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Sanitary ware dealer" },
  { name: "Flexible connectors", category: "Plumbing & Sanitary", unit: "piece", typicalSupplier: "Plumbing supplier" },
  { name: "Water Heater (Instant 1.5KW)", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Electrical/Plumbing supplier" },
  { name: "Pump / Booster", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Plumbing supplier" },
  { name: "Taps / faucets", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Sanitary ware dealer" },
  { name: "Toilet set (combitem)", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Sanitary ware dealer" },
  { name: "Washbasin / Vanity bowl", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Sanitary ware dealer" },
  { name: "Stainless sink", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Sanitary ware dealer" },
  { name: "Kitchen Sink (Stainless)", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Sanitary ware dealer" },
  { name: "Water Storage Tank (1000L)", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Plumbing supplier" },
  { name: "Shower tray / Base/cubicle", category: "Plumbing & Sanitary", unit: "unit", typicalSupplier: "Sanitary ware dealer" },
  { name: "PVC glue / PTFE tape / hemp", category: "Plumbing & Sanitary", unit: "piece", typicalSupplier: "Plumbing supplier" },
  { name: "Sanitary silicone", category: "Plumbing & Sanitary", unit: "cartridge", typicalSupplier: "Plumbing supplier" },

  // Floor & Wall Coverings
  { name: "Porcelain tiles", category: "Floor & Wall Coverings", unit: "m²", typicalSupplier: "Tile shop" },
  { name: "Ceramic wall tiles", category: "Floor & Wall Coverings", unit: "m²", typicalSupplier: "Tile shop" },
  { name: "Ceramic Floor Tiles (600x600)", category: "Floor & Wall Coverings", unit: "m²", typicalSupplier: "Tile shop" },
  { name: "Porcelain Floor Tiles (600x600)", category: "Floor & Wall Coverings", unit: "m²", typicalSupplier: "Tile shop" },
  { name: "Natural stone", category: "Floor & Wall Coverings", unit: "m²", typicalSupplier: "Stone supplier" },
  { name: "Solid wood flooring", category: "Floor & Wall Coverings", unit: "m²", typicalSupplier: "Flooring supplier" },
  { name: "Laminate flooring (8mm)", category: "Floor & Wall Coverings", unit: "m²", typicalSupplier: "Flooring supplier" },
  { name: "LVT / Vinyl flooring (roll)", category: "Floor & Wall Coverings", unit: "m²", typicalSupplier: "Flooring supplier" },
  { name: "Sheet PVC flooring", category: "Floor & Wall Coverings", unit: "m²", typicalSupplier: "Flooring supplier" },
  { name: "Carpet", category: "Floor & Wall Coverings", unit: "m²", typicalSupplier: "Flooring supplier" },
  { name: "Self-levelling screed", category: "Floor & Wall Coverings", unit: "bag", typicalSupplier: "Building materials store" },
  { name: "Floor levelling compound", category: "Floor & Wall Coverings", unit: "bag", typicalSupplier: "Building materials store" },
  { name: "Primer / Undercoat", category: "Floor & Wall Coverings", unit: "L", typicalSupplier: "Paint dealer" },
  { name: "Tile adhesive (C2S)", category: "Floor & Wall Coverings", unit: "bag", typicalSupplier: "Tile shop" },
  { name: "Tile grout", category: "Floor & Wall Coverings", unit: "bag", typicalSupplier: "Tile shop" },
  { name: "Silicone Sealant", category: "Floor & Wall Coverings", unit: "cartridge", typicalSupplier: "Hardware store" },
  { name: "Ceiling Boards (PVC)", category: "Floor & Wall Coverings", unit: "sheet", typicalSupplier: "Ceiling supplier" },
  { name: "Ceiling Boards (Gypsum)", category: "Floor & Wall Coverings", unit: "sheet", typicalSupplier: "Ceiling supplier" },
  { name: "Bitumen Sealant", category: "Floor & Wall Coverings", unit: "L", typicalSupplier: "Hardware store" },
  { name: "Skirtings (tile/wood)", category: "Floor & Wall Coverings", unit: "m", typicalSupplier: "Flooring supplier" },
  { name: "Cladding / Decorative panels", category: "Floor & Wall Coverings", unit: "m²", typicalSupplier: "Cladding supplier" },
  { name: "Interior paint (matt/satin)", category: "Floor & Wall Coverings", unit: "L", typicalSupplier: "Paint dealer" },
  { name: "Interior Paint (Emulsion)", category: "Floor & Wall Coverings", unit: "L", typicalSupplier: "Paint dealer" },
  { name: "Exterior facade paint", category: "Floor & Wall Coverings", unit: "L", typicalSupplier: "Paint dealer" },
  { name: "Varnish / Wood stain", category: "Floor & Wall Coverings", unit: "L", typicalSupplier: "Paint dealer" },
  { name: "Wallpaper", category: "Floor & Wall Coverings", unit: "roll", typicalSupplier: "Wallpaper supplier" },
  { name: "Wallpaper paste", category: "Floor & Wall Coverings", unit: "bag", typicalSupplier: "Wallpaper supplier" },
  { name: "Interior Doors (flush)", category: "Floor & Wall Coverings", unit: "piece", typicalSupplier: "Joinery / door supplier" },

  // Hardware & Fasteners
  { name: "Door Locks & Handles", category: "Hardware & Fasteners", unit: "set", typicalSupplier: "Hardware store" },
  { name: "Wood screws (box)", category: "Hardware & Fasteners", unit: "kg", typicalSupplier: "Hardware store" },
  { name: "Self-drilling screws (metal)", category: "Hardware & Fasteners", unit: "kg", typicalSupplier: "Hardware store" },
  { name: "Wall plugs (nylon/metal)", category: "Hardware & Fasteners", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Chemical anchors + threaded rods", category: "Hardware & Fasteners", unit: "set", typicalSupplier: "Hardware store" },
  { name: "Bolts / Nuts / Washers", category: "Hardware & Fasteners", unit: "kg", typicalSupplier: "Hardware store" },
  { name: "Nails (box)", category: "Hardware & Fasteners", unit: "kg", typicalSupplier: "Hardware store" },
  { name: "Nails & Screws (Assorted)", category: "Hardware & Fasteners", unit: "kg", typicalSupplier: "Hardware store" },
  { name: "Rivets / inserts", category: "Hardware & Fasteners", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Hinges / butt hinges", category: "Hardware & Fasteners", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Angles / Brackets / Joist hangers", category: "Hardware & Fasteners", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Clamps / Collars", category: "Hardware & Fasteners", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Hooks / Eye bolts", category: "Hardware & Fasteners", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Adhesive tapes / Double-sided", category: "Hardware & Fasteners", unit: "roll", typicalSupplier: "Hardware store" },
  { name: "Adhesive/sealant (PU/Silicone)", category: "Hardware & Fasteners", unit: "cartridge", typicalSupplier: "Hardware store" },
  { name: "Abrasives (sheets/discs)", category: "Hardware & Fasteners", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Sandpaper (Assorted)", category: "Hardware & Fasteners", unit: "pack", typicalSupplier: "Hardware store" },
  { name: "Drill bits / Blades / Discs", category: "Hardware & Fasteners", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Strips / Rods", category: "Hardware & Fasteners", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Locks / Padlocks", category: "Hardware & Fasteners", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Hinges / Slides (furniture)", category: "Hardware & Fasteners", unit: "piece", typicalSupplier: "Hardware store" },

  // Exterior Materials & Roads & Utilities
  { name: "Interlocking pavers", category: "Exterior Materials & Roads & Utilities", unit: "m²", typicalSupplier: "Paver manufacturer" },
  { name: "Outdoor concrete slabs", category: "Exterior Materials & Roads & Utilities", unit: "m²", typicalSupplier: "Precast yard" },
  { name: "Paving Stones (interlocking)", category: "Exterior Materials & Roads & Utilities", unit: "m²", typicalSupplier: "Paver manufacturer" },
  { name: "Concrete kerbs", category: "Exterior Materials & Roads & Utilities", unit: "m", typicalSupplier: "Precast yard" },
  { name: "Drainage channels with grates", category: "Exterior Materials & Roads & Utilities", unit: "m", typicalSupplier: "Drainage supplier" },
  { name: "Inspection chambers (concrete/PVC)", category: "Exterior Materials & Roads & Utilities", unit: "piece", typicalSupplier: "Drainage supplier" },
  { name: "HDPE sanitation pipes", category: "Exterior Materials & Roads & Utilities", unit: "m", typicalSupplier: "Plumbing supplier" },
  { name: "PVC sanitation pipes", category: "Exterior Materials & Roads & Utilities", unit: "m", typicalSupplier: "Plumbing supplier" },
  { name: "Downpipes (90mm)", category: "Exterior Materials & Roads & Utilities", unit: "m", typicalSupplier: "Roofing supplier" },
  { name: "Geotextile (landscaping)", category: "Exterior Materials & Roads & Utilities", unit: "m²", typicalSupplier: "Landscaping supplier" },
  { name: "Decorative gravel", category: "Exterior Materials & Roads & Utilities", unit: "m³", typicalSupplier: "Landscaping supplier" },
  { name: "Gabion baskets", category: "Exterior Materials & Roads & Utilities", unit: "piece", typicalSupplier: "Landscaping supplier" },
  { name: "Exterior stone cladding", category: "Exterior Materials & Roads & Utilities", unit: "m²", typicalSupplier: "Stone supplier" },
  { name: "Stone Veneer (Facing)", category: "Exterior Materials & Roads & Utilities", unit: "m²", typicalSupplier: "Stone supplier" },
  { name: "Composite decking boards", category: "Exterior Materials & Roads & Utilities", unit: "m²", typicalSupplier: "Decking supplier" },
  { name: "Fencing mesh / Rigid panels", category: "Exterior Materials & Roads & Utilities", unit: "m²", typicalSupplier: "Fencing supplier" },
  { name: "Gutters (Aluminum 125mm)", category: "Exterior Materials & Roads & Utilities", unit: "m", typicalSupplier: "Roofing supplier" },
  { name: "Posts (metal/concrete)", category: "Exterior Materials & Roads & Utilities", unit: "piece", typicalSupplier: "Fencing supplier" },
  { name: "Gates / Wicket gates", category: "Exterior Materials & Roads & Utilities", unit: "piece", typicalSupplier: "Fencing supplier" },
  { name: "Security Door (Steel)", category: "Exterior Materials & Roads & Utilities", unit: "piece", typicalSupplier: "Door supplier" },
  { name: "Chain Link / Wire Mesh", category: "Exterior Materials & Roads & Utilities", unit: "m²", typicalSupplier: "Fencing supplier" },
  { name: "Outdoor lighting", category: "Exterior Materials & Roads & Utilities", unit: "unit", typicalSupplier: "Electrical supplier" },
  { name: "Perimeter drains", category: "Exterior Materials & Roads & Utilities", unit: "m", typicalSupplier: "Drainage supplier" },
  { name: "Exterior Paint (Weatherproof)", category: "Exterior Materials & Roads & Utilities", unit: "L", typicalSupplier: "Paint dealer" },
  { name: "Rainwater tank", category: "Exterior Materials & Roads & Utilities", unit: "unit", typicalSupplier: "Plumbing supplier" },
  { name: "Fibre Cement Cladding Boards", category: "Exterior Materials & Roads & Utilities", unit: "sheet", typicalSupplier: "Cladding supplier" },

  // Miscellaneous Materials
  { name: "Concrete admixtures (accelerator/plasticizer)", category: "Miscellaneous Materials", unit: "L", typicalSupplier: "Building materials store" },
  { name: "Protective Coatings Anti-moss / Anti-rust", category: "Miscellaneous Materials", unit: "L", typicalSupplier: "Hardware store" },
  { name: "Solvents / Degreasers", category: "Miscellaneous Materials", unit: "L", typicalSupplier: "Hardware store" },
  { name: "Cement haze remover", category: "Miscellaneous Materials", unit: "L", typicalSupplier: "Hardware store" },
  { name: "Masking tapes", category: "Miscellaneous Materials", unit: "roll", typicalSupplier: "Hardware store" },
  { name: "Protective tarpaulins", category: "Miscellaneous Materials", unit: "m²", typicalSupplier: "Hardware store" },
  { name: "Polyethylene protective films", category: "Miscellaneous Materials", unit: "m²", typicalSupplier: "Hardware store" },
  { name: "PPE: Gloves / Helmets / Goggles", category: "Miscellaneous Materials", unit: "piece", typicalSupplier: "Safety supplier" },
  { name: "Safety shoes", category: "Miscellaneous Materials", unit: "pair", typicalSupplier: "Safety supplier" },
  { name: "Scaffolding (Rent per week)", category: "Miscellaneous Materials", unit: "set/week", typicalSupplier: "Plant hire" },
  { name: "Ladder", category: "Miscellaneous Materials", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Trowels / Floats / Spatulas", category: "Miscellaneous Materials", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Levels / Tape measures / Chalk line", category: "Miscellaneous Materials", unit: "piece", typicalSupplier: "Hardware store" },
  { name: "Cordless drill/driver", category: "Miscellaneous Materials", unit: "piece", typicalSupplier: "Tool supplier" },
  { name: "Circular/Jigsaw saw", category: "Miscellaneous Materials", unit: "piece", typicalSupplier: "Tool supplier" },
  { name: "Generator", category: "Miscellaneous Materials", unit: "unit", typicalSupplier: "Tool supplier" },
  { name: "Extension cords", category: "Miscellaneous Materials", unit: "m", typicalSupplier: "Electrical supplier" },
  { name: "LED site floodlights", category: "Miscellaneous Materials", unit: "unit", typicalSupplier: "Electrical supplier" },
];