import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { Helmet } from 'react-helmet-async';
import { useTranslation } from 'react-i18next';
import { supabase } from '@/lib/customSupabaseClient';
import { useToast } from '@/components/ui/use-toast';
import Papa from 'papaparse';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Edit, Trash2, Upload, PlusCircle, Link as LinkIcon, Loader2 } from 'lucide-react';
import { motion } from 'framer-motion';
import { domusDbApi } from '@/api/domusDbApi';

const INVENTORY_UNITS = ["bag", "m³", "piece", "metre", "m²", "roll", "sheet", "panel", "tonne", "set", "pot", "pair", "litre", "kg", "day"];
const INVENTORY_CATEGORIES = ["Foundational", "Structural", "Interior Finishing", "Plumbing & Sanitary", "Exterior Finishing", "Electrical & Mechanical", "Consumables & Site", "Roofing", "Appliances", "General"];

const InventoryItemForm = ({ open, setOpen, item, suppliers, onUpdate }) => {
  const { t } = useTranslation('custom');
  const { toast } = useToast();
  const [formData, setFormData] = useState({});
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setFormData(item || { current_stock: 0 });
  }, [item]);

  const handleChange = (e) => {
    const { id, value } = e.target;
    setFormData(prev => ({ ...prev, [id]: value }));
  };

  const handleSelectChange = (id, value) => {
    setFormData(prev => ({ ...prev, [id]: value }));
  };

  const handleSubmit = async () => {
    setLoading(true);
    const payload = { ...formData };
    
    ['stock_threshold_min', 'reorder_qty', 'current_stock'].forEach(key => {
      payload[key] = payload[key] ? Number(payload[key]) : 0;
    });
    
    // The ID column is a UUID generated by the DB. We should not send it on insert.
    if (!item?.id) {
        delete payload.id;
    }

    const { error } = item?.id
      ? await supabase.from('inventory_items').update(payload).eq('id', item.id)
      : await supabase.from('inventory_items').insert([payload]);

    setLoading(false);
    if (error) {
      toast({ title: t('inventory.import_error'), description: error.message, variant: 'destructive' });
    } else {
      toast({ title: t('inventory.import_success'), description: `Item ${item?.id ? 'updated' : 'added'}.` });
      onUpdate();
      setOpen(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="sm:max-w-4xl">
        <DialogHeader>
          <DialogTitle>{item?.id ? t('inventory.edit_item_title') : t('inventory.add_item_title')}</DialogTitle>
          <DialogDescription>{t('inventory.item_form_desc')}</DialogDescription>
        </DialogHeader>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 py-4 max-h-[70vh] overflow-y-auto pr-2">
            {['material_code', 'material_name'].map(id => (
                 <div className="space-y-2" key={id}><Label htmlFor={id}>{t(`inventory.${id}`)}</Label><Input id={id} value={formData[id] || ''} onChange={handleChange} /></div>
            ))}
             <div className="space-y-2"><Label htmlFor="category">{t('inventory.category')}</Label><Select onValueChange={(v) => handleSelectChange('category', v)} value={formData.category}><SelectTrigger><SelectValue placeholder={t('inventory.select_category')} /></SelectTrigger><SelectContent>{INVENTORY_CATEGORIES.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div>
             <div className="space-y-2"><Label htmlFor="unit">{t('inventory.unit')}</Label><Select onValueChange={(v) => handleSelectChange('unit', v)} value={formData.unit}><SelectTrigger><SelectValue placeholder={t('inventory.select_unit')} /></SelectTrigger><SelectContent>{INVENTORY_UNITS.map(u => <SelectItem key={u} value={u}>{u}</SelectItem>)}</SelectContent></Select></div>
            {['stock_threshold_min', 'reorder_qty', 'current_stock'].map(id => (
                 <div className="space-y-2" key={id}><Label htmlFor={id}>{t(`inventory.${id === 'stock_threshold_min' ? 'min_stock' : id}`)}</Label><Input id={id} type="number" value={formData[id] || ''} onChange={handleChange} /></div>
            ))}
            <div className="space-y-2"><Label htmlFor="primary_supplier_code">{t('inventory.primary_supplier')}</Label><Select onValueChange={(v) => handleSelectChange('primary_supplier_code', v)} value={formData.primary_supplier_code}><SelectTrigger><SelectValue placeholder={t('inventory.select_supplier')} /></SelectTrigger><SelectContent>{suppliers.map(s => <SelectItem key={s.supplier_code} value={s.supplier_code}>{s.supplier_name}</SelectItem>)}</SelectContent></Select></div>
            <div className="space-y-2"><Label htmlFor="backup_supplier_code">{t('inventory.backup_supplier')}</Label><Select onValueChange={(v) => handleSelectChange('backup_supplier_code', v)} value={formData.backup_supplier_code}><SelectTrigger><SelectValue placeholder={t('inventory.select_supplier')} /></SelectTrigger><SelectContent>{suppliers.map(s => <SelectItem key={s.supplier_code} value={s.supplier_code}>{s.supplier_name}</SelectItem>)}</SelectContent></Select></div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => setOpen(false)}>{t('materials.cancel')}</Button>
          <Button onClick={handleSubmit} disabled={loading}> {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null} {t('materials.save')}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

const ImportDialog = ({ onUpdate, onImportComplete }) => {
  const { t } = useTranslation('custom');
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const [importType, setImportType] = useState('suppliers');
  const [file, setFile] = useState(null);
  const [loading, setLoading] = useState(false);

  const importOrder = ['suppliers', 'inventory_items', 'material_purchases', 'grn', 'gin', 'stock_movements'];
  const tableMap = {
    suppliers: 'suppliers',
    inventory_items: 'inventory_items',
    material_purchases: 'material_purchases',
    grn: 'grn',
    gin: 'gin',
    stock_movements: 'stock_movements'
  };
  const conflictMap = {
      suppliers: 'supplier_code',
      inventory_items: 'material_code',
      material_purchases: 'purchase_id',
      grn: 'grn_id',
      gin: 'gin_id',
      stock_movements: 'movement_id',
  };

  const handleImport = () => {
    if (!file) return;
    setLoading(true);
    Papa.parse(file, {
      header: true,
      skipEmptyLines: true,
      transformHeader: header => header.toLowerCase().replace(/ /g, '_'),
      complete: async (results) => {
        const { data } = results;
        const tableName = tableMap[importType];
        const conflictColumn = conflictMap[importType];

        let processedData = data.map(row => {
           let newRow = {...row};
           if (newRow.categories_served && typeof newRow.categories_served === 'string') {
              newRow.categories_served = newRow.categories_served.split(',').map(s => s.trim());
           }
           // Convert numeric fields
           Object.keys(newRow).forEach(key => {
             if (['stock_threshold_min', 'reorder_qty', 'quantity', 'unit_price', 'qty_received', 'qty_issued'].includes(key)) {
                 newRow[key] = Number(newRow[key]) || 0;
             }
           });
           return newRow;
        });

        const { error } = await supabase.from(tableName).upsert(processedData, { onConflict: conflictColumn });
        
        setLoading(false);
        if (error) {
          toast({ title: t('inventory.import_error'), description: error.message, variant: 'destructive' });
        } else {
          toast({ title: t('inventory.import_success'), description: `${data.length} records imported to ${tableName}.` });
          onUpdate(); // General refresh
          if(onImportComplete) onImportComplete(); // Specific callback
          setOpen(false);
          setFile(null);
        }
      }
    });
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline"><Upload className="mr-2 h-4 w-4" />{t('inventory.import_data')}</Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t('inventory.import_dialog_title')}</DialogTitle>
          <DialogDescription>{t('inventory.import_dialog_desc')}</DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-4">
          <div className="space-y-2"><Label>{t('inventory.import_type')}</Label>
          <Select value={importType} onValueChange={setImportType}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>
            {importOrder.map(type => <SelectItem key={type} value={type}>{t(`inventory.import_${type}`)}</SelectItem>)}
          </SelectContent></Select></div>
          <div className="space-y-2"><Label>{t('inventory.upload_file')}</Label><Input type="file" accept=".csv" onChange={(e) => setFile(e.target.files[0])} /></div>
        </div>
        <DialogFooter>
          <Button onClick={handleImport} disabled={!file || loading}>{loading ? <><Loader2 className="mr-2 h-4 w-4 animate-spin"/> {t('inventory.importing')}</> : t('inventory.import_data')}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

const InventoryPage = () => {
  const { t, i18n } = useTranslation(['custom', 'translation']);
  const { toast } = useToast();
  const [items, setItems] = useState([]);
  const [suppliers, setSuppliers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ category: 'all', supplier: 'all', stock: 'all' });
  const [formOpen, setFormOpen] = useState(false);
  const [selectedItem, setSelectedItem] = useState(null);
  const [deleteAlertOpen, setDeleteAlertOpen] = useState(false);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const [itemsData, suppliersData] = await Promise.all([
        domusDbApi.getInventoryItems(),
        domusDbApi.getSuppliers()
      ]);

      // Manually join supplier names for display
      const processedItems = itemsData.map(item => ({
        ...item,
        primary_supplier: suppliersData.find(s => s.supplier_code === item.primary_supplier_code),
        backup_supplier: suppliersData.find(s => s.supplier_code === item.backup_supplier_code),
      }));

      setItems(processedItems);
      setSuppliers(suppliersData);
    } catch (error) {
      toast({ title: "Error fetching data", description: error.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  }, [toast]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const filteredItems = useMemo(() => {
    return items.filter(item => {
      const categoryMatch = filters.category === 'all' || item.category === filters.category;
      const supplierMatch = filters.supplier === 'all' || item.primary_supplier_code === filters.supplier;
      const stockMatch = filters.stock === 'all' || (filters.stock === 'low' ? item.current_stock < item.stock_threshold_min : item.current_stock >= item.stock_threshold_min);
      return categoryMatch && supplierMatch && stockMatch;
    });
  }, [items, filters]);

  const handleEdit = (item) => {
    setSelectedItem(item);
    setFormOpen(true);
  };
  
  const handleAdd = () => {
    setSelectedItem(null);
    setFormOpen(true);
  };

  const handleDelete = (item) => {
    setSelectedItem(item);
    setDeleteAlertOpen(true);
  };

  const confirmDelete = async () => {
    const { error } = await supabase.from('inventory_items').delete().eq('id', selectedItem.id);
    if (error) {
      toast({ title: t('inventory.import_error'), description: error.message, variant: 'destructive' });
    } else {
      toast({ title: t('inventory.import_success'), description: "Item deleted." });
      fetchData();
    }
    setDeleteAlertOpen(false);
  };

  return (
    <>
      <Helmet>
        <html lang={i18n.language} />
        <title>{t('inventory.title', { ns: 'custom' })} - DomusBuilder Hub</title>
        <meta name="description" content={t('inventory.description', { ns: 'custom' })} />
      </Helmet>
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="space-y-6 p-4 md:p-6">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div><h1 className="text-3xl font-bold text-gray-800">{t('inventory.title')}</h1><p className="text-gray-500 mt-1">{t('inventory.description')}</p></div>
          <div className="flex gap-2"><ImportDialog onUpdate={fetchData} /><Button onClick={handleAdd}><PlusCircle className="mr-2 h-4 w-4" />{t('inventory.add_item')}</Button></div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Select value={filters.category} onValueChange={(v) => setFilters(f => ({...f, category: v}))}><SelectTrigger><SelectValue placeholder={t('inventory.filter_by_category')} /></SelectTrigger><SelectContent><SelectItem value="all">{t('inventory.all_categories')}</SelectItem>{INVENTORY_CATEGORIES.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select>
          <Select value={filters.supplier} onValueChange={(v) => setFilters(f => ({...f, supplier: v}))}><SelectTrigger><SelectValue placeholder={t('inventory.filter_by_supplier')} /></SelectTrigger><SelectContent><SelectItem value="all">{t('inventory.all_suppliers')}</SelectItem>{suppliers.map(s => <SelectItem key={s.supplier_code} value={s.supplier_code}>{s.supplier_name}</SelectItem>)}</SelectContent></Select>
          <Select value={filters.stock} onValueChange={(v) => setFilters(f => ({...f, stock: v}))}><SelectTrigger><SelectValue placeholder={t('inventory.filter_by_stock')} /></SelectTrigger><SelectContent><SelectItem value="all">{t('inventory.all_stock')}</SelectItem><SelectItem value="low">{t('inventory.low_stock')}</SelectItem><SelectItem value="in_stock">{t('inventory.in_stock')}</SelectItem></SelectContent></Select>
        </div>

        <div className="bg-white rounded-lg shadow-sm overflow-hidden border">
          <Table>
            <TableHeader><TableRow><TableHead>{t('inventory.material_code')}</TableHead><TableHead>{t('inventory.material_name')}</TableHead><TableHead>{t('inventory.current_stock')}</TableHead><TableHead>{t('inventory.min_stock')}</TableHead><TableHead>{t('inventory.reorder_qty')}</TableHead><TableHead>{t('inventory.primary_supplier')}</TableHead><TableHead>{t('inventory.backup_supplier')}</TableHead><TableHead>{t('inventory.actions')}</TableHead></TableRow></TableHeader>
            <TableBody>
              {loading ? <TableRow><TableCell colSpan="8" className="text-center py-8"><Loader2 className="mx-auto h-8 w-8 animate-spin text-blue-600" /></TableCell></TableRow>
               : filteredItems.map(item => (
                <TableRow key={item.id}>
                  <TableCell>
                      <Badge variant={item.current_stock < item.stock_threshold_min ? 'destructive' : 'secondary'}>{item.material_code}</Badge>
                      {item.current_stock < item.stock_threshold_min && item.stock_threshold_min > 0 && <Badge variant="destructive" className="ml-2">Low Stock</Badge>}
                  </TableCell>
                  <TableCell className="font-medium">{item.material_name}</TableCell>
                  <TableCell>{item.current_stock || 0} {item.unit}</TableCell>
                  <TableCell>{item.stock_threshold_min}</TableCell>
                  <TableCell>{item.reorder_qty}</TableCell>
                  <TableCell>{item.primary_supplier?.supplier_name || item.primary_supplier_code}{item.primary_supplier?.website && <a href={item.primary_supplier.website} target="_blank" rel="noopener noreferrer"><LinkIcon className="h-3 w-3 inline ml-1 text-blue-500"/></a>}</TableCell>
                  <TableCell>{item.backup_supplier?.supplier_name || item.backup_supplier_code}{item.backup_supplier?.website && <a href={item.backup_supplier.website} target="_blank" rel="noopener noreferrer"><LinkIcon className="h-3 w-3 inline ml-1 text-blue-500"/></a>}</TableCell>
                  <TableCell className="space-x-2"><Button size="sm" variant="outline" onClick={() => handleEdit(item)}><Edit className="h-4 w-4 mr-1" />{t('inventory.edit')}</Button><Button size="sm" variant="destructive" onClick={() => handleDelete(item)}><Trash2 className="h-4 w-4 mr-1" />{t('inventory.delete')}</Button></TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </motion.div>
      <InventoryItemForm open={formOpen} setOpen={setFormOpen} item={selectedItem} suppliers={suppliers} onUpdate={fetchData} />
      <AlertDialog open={deleteAlertOpen} onOpenChange={setDeleteAlertOpen}>
        <AlertDialogContent>
          <AlertDialogHeader><AlertDialogTitle>{t('inventory.delete_confirm_title')}</AlertDialogTitle><AlertDialogDescription>{t('inventory.delete_confirm_desc')}</AlertDialogDescription></AlertDialogHeader>
          <AlertDialogFooter><AlertDialogCancel>{t('materials.cancel')}</AlertDialogCancel><AlertDialogAction onClick={confirmDelete}>{t('inventory.delete')}</AlertDialogAction></AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
};

export default InventoryPage;